

export const ActionTypes = {
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAIL: 'GET_PRODUCTS_FAIL',
    LOADING: 'LOADING',
    ADD_TRANSPORT_TO_ADMIN_PANEL: 'ADD_TRANSPORT_TO_ADMIN_PANEL',
    GET_LOGIN_USERS_SUCCESS: 'GET_LOGIN_USERS_SUCCESS',
    GET_LOGIN_USERS_FAIL: 'GET_LOGIN_USERS_FAIL',
    TRANSPORT_APPROVED: 'TRANSPORT_APPROVED',
    TRANSPORT_REJECTED: 'TRANSPORT_REJECTED',
    GET_APPROVED_TRANSPORT_SUCCESS: 'GET_APPROVED_TRANSPORT_SUCCESS',
    GET_APPROVED_TRANSPORT_FAIL: 'GET_APPROVED_TRANSPORT_FAIL',
    GET_TRANSPORT_TO_APPROVE_SUCCESS: 'GET_TRANSPORT_TO_APPROVE_SUCCESS',
    GET_TRANSPORT_TO_APPROVE_FAIL: 'GET_TRANSPORT_TO_APPROVE_FAIL',
}